### ISSUE TITLE
There is an issue with types for test file

### ISSUE THREAD

**Issue by ahmad-everneat** [reduxjs/redux-templates#124] opened 2024-03-25 04:02 UTC
![Capture](https://github.com/reduxjs/redux-templates/assets/152980859/6f1c8350-5715-4027-b5f0-1d9ced028480)
npm run type-check is giving errors

**Comment by aryaemami59** [comment] 2024-03-25 05:11
This issue was caused by Vitest in https://github.com/vitest-dev/vitest/pull/5142, I have submitted a [PR](https://github.com/vitest-dev/vitest/pull/5415) to fix this on Vitest's end. I addressed it in this repo on #118, but I might have to put up a separate PR just for the fix. In the meantime you can do this:


```ts
const it = test<LocalTestContext>

describe('counter reducer', () => {
  beforeEach<LocalTestContext>((context) => {
    const initialState: CounterSliceState = {
      value: 3,
      status: 'idle',
    }

    const store = makeStore({ counter: initialState })

    context.store = store
  })
```

**Comment by EskiMojo14** [comment] 2024-03-25 16:02
in all honesty i'm not sure of the benefit of using the context object vs just having a let variable that gets reassigned 😕

**Comment by aryaemami59** [comment] 2024-03-26 01:15
@EskiMojo14 We can do that too, we can also use a fixture, I only suggested it because it seemed to fix the problem with the least number of lines changed.

**Closed** 2024-03-26 20:15 UTC

**Comment by aryaemami59** [comment] 2024-03-27 08:02
looks like https://github.com/vitest-dev/vitest/pull/5142 was merged so hopefully with the next release of Vitest, this will not be an issue anymore.
